### ISSUE TITLE
ContEst refactor

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/gatk-protected#771] opened 2016-11-14 21:11 UTC
@ldgauthier commented on [Fri Jul 10 2015](https://github.com/broadinstitute/gsa-unstable/issues/1045)

Clean up port of code from ContEst repo.
Document different tool modes (i.e. sample/lane/meta, populations to evaluate, etc.)
Add argument documentation.

---

@vdauwera commented on [Tue Jul 14 2015](https://github.com/broadinstitute/gsa-unstable/issues/1045#issuecomment-121371879)

Can we rename ContaminationWalker to something more explicit and that doesn't have "walker" in the name, such as e.g. EstimateContamination or ContaminationEstimator? 

Docs look pretty good, will plan to do a more detailed pass when it gets moved to protected, but right now it's probably got some of the best docs in private ;)

---

@vdauwera commented on [Tue Jul 14 2015](https://github.com/broadinstitute/gsa-unstable/issues/1045#issuecomment-121372170)

Btw, do you mind if I label this sort of issue M2, since it's part of essentially the same effort? 

---

@ldgauthier commented on [Tue Jul 14 2015](https://github.com/broadinstitute/gsa-unstable/issues/1045#issuecomment-121372861)

Hrmmmm... It's really not, though.  Most people invested in M2 progress don't care if ContEst gets ported.  Can we give it a GATK3.5 label?

---

@vdauwera commented on [Tue Jul 14 2015](https://github.com/broadinstitute/gsa-unstable/issues/1045#issuecomment-121380872)

Ah. I just lump it in as "stuff used in the somatic world". I'll add it to the soon-to-be-created 3.5 milestone, that's work well enough I think. 

---

@ldgauthier commented on [Fri Jul 17 2015](https://github.com/broadinstitute/gsa-unstable/issues/1045#issuecomment-122359072)

Other comments from @yfarjoun:
- "genoptype" typo in on-the-fly commandline around line 112 in ContaminationWalker.java
- How easy/difficult would it be to allow this to be collected per-library?
- it looks like the assumption here is that the probability of an alt at a site is always maf, this assume independence of the alleles at a given site, which, of course, isn't true if the contaminator is a single individual (the most likely case). Wouldn't it be better to split this into the 3 contaminator genotypes and sum over these?
- It's strange that the population fit is updated for every possible contamination rate and for every base...is this right?

---

@vdauwera commented on [Tue Nov 03 2015](https://github.com/broadinstitute/gsa-unstable/issues/1045#issuecomment-153556966)

@ldgauthier Can I assume this is finished?

---

@ldgauthier commented on [Wed Nov 04 2015](https://github.com/broadinstitute/gsa-unstable/issues/1045#issuecomment-153712984)

You know what happens when you assume!

I don't think I ever started this.

---

@vdauwera commented on [Wed Nov 04 2015](https://github.com/broadinstitute/gsa-unstable/issues/1045#issuecomment-153752127)

Hah ok so much for that then...

---

@vdauwera commented on [Mon Nov 14 2016](https://github.com/broadinstitute/gsa-unstable/issues/1045#issuecomment-260463855)

Moving this to GATK4 on the assumption that someone might care there.

**Comment by davidbenjamin** [comment] 2016-11-20 06:18
As it turns out, people decided that ContEst falls under the Mutect team's responsibilities and it's on our quarterly goals.  Duplicate of #791.

**Closed by davidbenjamin** 2016-11-20 06:18 UTC
