### ISSUE TITLE
TangentNormalization logic in Spark not exactly the same as for non-Spark, does that matter?

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#280] opened 2016-01-06 17:46 UTC
The non-spark tangent normalization (in PoN.java) looks at targets that need to be pruned.  The spark version does not.  Is there ever a case where targets need to be pruned?  Could we impute ahead of time and then run the same logic?

**Comment by LeeTL1220** [comment] 2016-01-06 17:47
All unit tests pass with Spark version active, which leads me to believe that there is no difference in our test set.  Is that a problem itself?

**Comment by vruano** [comment] 2016-01-07 16:24
I guess something is not been covered by test then. Not a bug, but an enhancement.

**Comment by davidbenjamin** [comment] 2016-11-03 13:46
@samuelklee Should we close this since the new coverage model will moot it?

**Closed** 2016-11-03 14:02 UTC
Labels: Copy Number tools, question
