### ISSUE TITLE
Separate male and female PoNs

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#229] opened 2015-12-04 01:57 UTC
This would allow us to do copy number analysis on X and Y chromosomes.  Currently, this is only supported by having the user create two separate PoNs for male and female and then determining which PoN to use for each case sample.

Details of implementation must also be fleshed out, since this is a conceptually simple issue, but needs to be as easy as possible for the user.

**Comment by davidbenjamin** [comment] 2016-06-07 06:52
@mbabadi's masking matrix enhancement to the new coverage model will handle this very cleanly.  Close this issue once it is adopted.

**Comment by samuelklee** [comment] 2016-08-17 20:10
Essentially a duplicate of #526.

**Closed by samuelklee** 2016-08-17 20:10 UTC
Labels: Copy Number tools
